Api:
  Version: "1.0"
  LastUpdate: 2024-07-16
  Author: "Dexu"

Clients:
  dexu:
    username: "dexu"
    authToken: "352-FSD-3FD-3GD-3GH"
    license:
      type: "Premium"
      validUntil: "2025-07-15"
  fnoksu:
    username: "fnoksu"
    authToken: "378X-DgSD-543D-XA"
    license:
      type: "Standard"
      validUntil: "2024-12-31"
